plugin: amazon.aws.aws_ec2

regions:
  - eu-west-1

filters:
  tag:Ansible: "true"
  instance-state-name: running

keyed_groups:
  - key: tags.Role
    prefix: role
    separator: "_"

compose:
  ansible_host: public_ip_address
  rd_tags: tags