apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: task1-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  clusterIP: None # Headless service for stable DNS
  selector:
    app: redis

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: task1-redis
data:
  redis.conf: |
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    cluster-require-full-coverage no
    
    appendonly yes
    appendfsync everysec

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: task1-redis
spec:
  serviceName: "redis"
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2
          command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /usr/local/etc/redis
      volumes:
        - name: config
          configMap:
            name: redis-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests: 
            storage: 5Gi
